server:
  port: 9080

spring:
  application:
    name: producer-kafka

kafka:
  bootstrap-servers: ark-01.srvs.cloudkafka.com:9094, ark-02.srvs.cloudkafka.com:9094, ark-03.srvs.cloudkafka.com:9094
  producer:
    topic: ${CLOUDKARAFKA_USERNAME}-news.json
    num-partitions: 5
  configuration:
    security.protocol: SASL_SSL
    sasl:
      mechanism: SCRAM-SHA-256
      jaas.config: org.apache.kafka.common.security.scram.ScramLoginModule required username="${CLOUDKARAFKA_USERNAME}" password="${CLOUDKARAFKA_PASSWORD}";

