server:
  port: 9082

spring:
  application:
    name: producer-cloud-stream
  cloud:
    stream:
      kafka:
        binder:
          brokers: ${KAFKA_HOST:localhost}:${KAFKA_PORT:29092}
      bindings:
        output:
          destination: news.json
          content-type: application/json
          producer:
            partition-key-expression: headers['partitionKey']
            partition-count: 5

---
spring:
  profiles: cloudkarafka
  cloud:
    stream:
      kafka:
        binder:
          brokers: ark-01.srvs.cloudkafka.com:9094, ark-02.srvs.cloudkafka.com:9094, ark-03.srvs.cloudkafka.com:9094
          configuration:
            security.protocol: SASL_SSL
            sasl:
              mechanism: SCRAM-SHA-256
              jaas.config: org.apache.kafka.common.security.scram.ScramLoginModule required username="${CLOUDKARAFKA_USERNAME}" password="${CLOUDKARAFKA_PASSWORD}";
      bindings:
        output:
          destination: ${CLOUDKARAFKA_USERNAME}-news.json
