server:
  port: 9081

spring:
  application:
    name: consumer

kafka:
  bootstrap-servers: ark-01.srvs.cloudkafka.com:9094, ark-02.srvs.cloudkafka.com:9094, ark-03.srvs.cloudkafka.com:9094
  consumer:
    group-id: consumer-group
    auto-offset-reset: earliest
    topic: ${CLOUDKARAFKA_USERNAME}-news.json
  secure-connection:
    enabled: true
    security.protocol: SASL_SSL
    sasl:
      mechanism: SCRAM-SHA-256
      jaas.config: org.apache.kafka.common.security.scram.ScramLoginModule required username="${CLOUDKARAFKA_USERNAME}" password="${CLOUDKARAFKA_PASSWORD}";
